Improve UnionFind::invariant() implementation.
matthewbdwyer/tipc pull request #104
Opened 2024-07-27 05:58 UTC by shahryarkiani

Two main changes, removed unnecessary copying and refactored for-loop to remove redundant equality checks.

2024-07-31 14:34 UTC, matthewbdwyer requested changes
Thanks for the loop refactor.  It looks good to me.  Your comment stated that you removed an unnecessary copy, but I don't see that.   Is that something that you forgot to include or is the comment on the PR out of date.

2024-07-31 15:17 UTC, shahryarkiani commented
By that I was referring to changing the edge1 and edge2 variables from `auto edge1 : edges` to `const auto& edge1 = *outerIter`. I think it's a smaller boost anyways(since we were only copying the shared_ptr). I can add a benchmark test to this PR to show the change.

2024-08-01 13:42 UTC, matthewbdwyer commented
I see.   Yes that makes sense.  I don't think we need a performance test for this.  It looks equivalent to me and as long as all of the test pass I think we are good.

2024-08-01 13:43 UTC, matthewbdwyer approved these changes

2024-08-01 13:43 UTC, merged